import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "../globals.css";
import {Footer} from "@/shared/layout/Footer";
import {AuthProvider} from "@/shared/layout/AuthProvider";
import {Sidebar} from "@/shared/layout/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            <AuthProvider>
                <div className="flex min-h-screen bg-[#fcfdfd]">
                    <Sidebar />
                    {children}
                </div>
            </AuthProvider>
            <Footer />
        </body>
    </html>
  );
}
