version: '3.8'

services:
  # --- Add Redis Service ---
  redis-cache:
    image: redis:7-alpine # Using Redis 7 on Alpine base
    container_name: redis-cache
    ports:
      - "6379:6379" # Expose default Redis port
    command: redis-server --appendonly yes # Enable AOF persistence (optional but often good)
    volumes:
      - redis_data:/data # Persist data in /data directory inside container
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"  # CQL port
    environment:
      - CASSANDRA_CLUSTER_NAME=dev-cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 10s
      timeout: 10s
      retries: 5

# Define named volumes for data persistence
volumes:
  redis_data:
  cassandra_data:
