apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend.yml
  - pg-deployment.yml
  - otel-collector.yml

configMapGenerator:
  - name: otel-collector-config
    files:
      - config.yaml

generatorOptions:
  disableNameSuffixHash: true
