apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyurl-server-deployment
  labels:
    app: tinyurl-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyurl-server
  template:
    metadata:
      labels:
        app: tinyurl-server
    spec:
      containers:
        - name: tinyurl-server
          image: chuotcona123/tinyurl-server:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "2"
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3000"
              # REDIS
            - name: REDIS_URL
              value: redis://redis:6379

            - name: CASSANDRA_CONTACT_POINTS
              value: cassandra
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

---
apiVersion: v1
kind: Service
metadata:
  name: tinyurl-service
spec:
  type: NodePort
  selector:
    app: tinyurl-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30101

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "3"
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tinyurl-service
                port:
                  number: 3000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tinyurl-server-autoscaler
  labels:
    app: tinyurl-server
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tinyurl-server-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleDown:
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
        - type: Percent
          value: 40
          periodSeconds: 60
