query SearchTotesDashboard($getTotesInput: GetTotesInput!) {
    totes(getTotesInput: $getTotesInput) {
        id
        name
        color
        description
        bannerURL
        price
        rating
        size
        style
        inStock
        isBestSeller
        isNewArrival
        material
    }
}

query GetQuickViewTote($id: String!) {
    tote(id: $id) {
        id
        name
        color
        description
        bannerURL
        price
        rating
        size
        style
        inStock
        isBestSeller
        isNewArrival
        material
    }
}
