name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - tinyurl-server

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node: [22.x]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/tinyurl-client/node_modules/
          key: cache-node-modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            - cache-node-modules-

      - name: Setup packages
        working-directory: ${{ github.workspace }}/tinyurl-client
        run: |
          pnpm install --frozen-lockfile
          pnpm audit --audit-level=critical

  cd:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node: [ 22.x ]

    steps:
      - name: 🧹 Checkout code
        uses: actions/checkout@v3

      - name: 🐳 Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🔧 Build and tag image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tinyurl-server:latest tinyurl-server

      - name: 📤 Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/tinyurl-server:latest